---
- name: Create FlexVol
  na_ontap_volume:
    state: present
    name: "{{ vol_name }}"
    is_infinite: False
    aggregate_name: "{{ aggr_name }}"
    size: "{{ vol_size }}"
    size_unit: "{{ vol_size_unit }}"
    space_guarantee: none
    policy: default
    volume_security_style: ntfs
    percent_snapshot_space: 60
    vserver: "{{ vserver_name }}"
    wait_for_completion: True
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
