---
# tasks file for netapp_cifs
- include_tasks: create_aggr.yml
  when: create_aggr| bool
- include_tasks: create_svm.yml
  when: create_svm| bool
- include_tasks: create_broadcast.yml
  when: create_broadcast | bool
- include_tasks: create_interface.yml
  when: create_interface | bool
- include_tasks: create_vol.yml
  when: create_vol | bool
- include_tasks: create_cifs.yml
  when: create_cifs | bool
- include_tasks: create_share.yml
  when: create_share | bool
- include_tasks: enable_user.yml
  when: enable_user | bool